#!/usr/bin/env node
const packager = require("electron-packager");
const pkg = require("../../application/package.json");

packager({
    name: "kobito",
    dir: "./browser",
    out: "./dist",
    icon: "./assets/icon.ico",
    platform: "darwin",
    arch: "x64",
    version: "1.6.0",
    overwrite: true,
    asar: true,
    "app-version": pkg.version,
    "app-copyright": "Copyright (C) 2017 Increments Inc."
}, function (err, appPaths) {
    if (err) console.log(err);
    console.log("Done: " + appPaths);
});
